[package]
name = "ImportGraphTS"
version = "0.1.0"
edition = "2024"

[dependencies]
glob = "0.3.2"
serde = {version = "1.0.219", feature = "serde_derive" }
serde_derive = "1.0.219"
serde_json = "1.0.140"
